Algoritmo "leia o nome"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/02/2026
Var
// Seção de Declarações das variáveis 
 nome : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("digite seu nome: ")
  leia (nome)
  escreva("olá ",nome," seja bem vindo")

Fimalgoritmo